### PR TITLE
Update template to use equinix provider

### PR DESCRIPTION
**Pull request by ocobles**
- @pulumi/equinix-metal" replaced with "@equinix-labs/pulumi-equinix"
- Cloud-init configuration updated to match https://github.com/equinix-labs/terraform-equinix-kubernetes-cluster/ steps (+ CNI Cilium and Ambassador Edge Stack)
- kubernetesVersion defaults to 1.24.7 (new issue is required to certify compatibility with higher versions)
- Updated pulumi/TLS configuration to suppress deprecation warnings
- Parametrized configuration to differentiate primary/replicas control-plane nodes
- Kube-vip version hardcoded to v0.5.12 (new issue is required to parameterize the kube-vip version and certify compatibility with higher versions)
- OS version fixed to Ubuntu2204

### CODE REVIEW

**Comment by ctreatma** [comment]
I'm not sure how to review this effectively.  Are there steps I should follow to run it locally?

**Comment by cprivitere** [comment]
Ok, can confirm that the cluster comes up but it's not fully healthy. 

```
root@example-control-plane-1:~# kubectl get pods -A
NAMESPACE     NAME                                              READY   STATUS    RESTARTS      AGE
ambassador    ambassador-55f69bc4c6-bpxpw                       0/1     Running   5 (73s ago)   6m27s
ambassador    ambassador-agent-5648df689b-bsxcj                 1/1     Running   0             6m27s
ambassador    ambassador-redis-75d95f7cdf-wds4c                 1/1     Running   0             6m27s
kube-system   cilium-jx7zf                                      1/1     Running   0             6m27s
kube-system   cilium-operator-864f5d87f8-jvhjn                  1/1     Running   0             6m27s
kube-system   cilium-operator-864f5d87f8-sxn7h                  1/1     Running   0             6m27s
kube-system   cilium-qg45f                                      1/1     Running   0             5m5s
kube-system   cilium-std95                                      1/1     Running   0             5m5s
kube-system   coredns-6d4b75cb6d-bwldx                          0/1     Running   2 (44s ago)   6m27s
kube-system   coredns-6d4b75cb6d-dg9w8                          0/1     Running   2 (54s ago)   6m27s
kube-system   etcd-example-control-plane-1                      1/1     Running   0             6m40s
kube-system   kube-apiserver-example-control-plane-1            1/1     Running   0             6m39s
kube-system   kube-controller-manager-example-control-plane-1   1/1     Running   0             6m39s
kube-system   kube-scheduler-example-control-plane-1            1/1     Running   0             6m41s
kube-system   kube-vip-example-control-plane-1                  1/1     Running   0             6m43s
```

**Comment by cprivitere** [comment]
```
root@example-control-plane-1:~/cilium-cli# ./cilium  status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         10 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 3, Ready: 3/3, Available: 3/3
Deployment        cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Containers:       cilium             Running: 3
                  cilium-operator    Running: 2
Cluster Pods:     7/7 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.10.2@sha256:1112a29c8fe04c2a47e5e250112a940c9b81d6700b7e8bba159ab996a05282b9: 3
                  cilium-operator    quay.io/cilium/operator-generic:v1.10.2@sha256:a88b04cb5895610620da6e90d362af9e512d2baa51a0a0d77ab34186dfb20c68: 2
Errors:           cilium             cilium-jx7zf    controller endpoint-1586-regeneration-recovery is failing since 0s (2x): regeneration recovery failed
                  cilium             cilium-jx7zf    controller cilium-health-ep is failing since 3s (70x): Get "http://10.0.0.134:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-qg45f    controller endpoint-1403-regeneration-recovery is failing since 5s (4x): regeneration recovery failed
                  cilium             cilium-qg45f    controller endpoint-905-regeneration-recovery is failing since 8s (9x): regeneration recovery failed
                  cilium             cilium-qg45f    controller cilium-health-ep is failing since 22s (69x): Get "http://10.0.1.217:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-qg45f    controller endpoint-3133-regeneration-recovery is failing since 10s (4x): regeneration recovery failed
                  cilium             cilium-std95    controller endpoint-3462-regeneration-recovery is failing since 8s (4x): regeneration recovery failed
                  cilium             cilium-std95    controller endpoint-936-regeneration-recovery is failing since 9s (9x): regeneration recovery failed
                  cilium             cilium-std95    controller endpoint-9-regeneration-recovery is failing since 13s (9x): regeneration recovery failed
                  cilium             cilium-std95    controller cilium-health-ep is failing since 20s (69x): Get "http://10.0.2.13:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by ocobles** [comment]
@cprivitere last two commits should fix it. As agreed internally, I have removed the ingress controller configuration for now. Cilium was misconfigured, it was using a different subnet than the one defined for ClusterConfiguration. I ran into some issues updating to last release 1.13.3, `clusterPoolIPv4PodCIDR` is now deprecated in favor of `clusterPoolIPv4PodCIDRList`. MTU is not detected correctly (not sure why and will require some investigation, but it works fine specifying it).`kubeProxyReplacement=probe` no longer exists, to achieve same behavior with `kubeProxyReplacement=partial` it requires some extra config 
```
    --set nodePort.enabled=true \
    --set nodePort.enableHealthCheck=false \
    --set hostServices.enabled=true \
    --set externalIPs.enabled=true \
    --set hostPort.enabled=true \
```

**Comment by cprivitere** [comment]
Looking good now!

**Review by cprivitere — APPROVED** [review]

**Pull request merged**
