### PR TITLE
Added a python template

### PR DESCRIPTION
**Pull request by ocobles**
Added a template to replicate the same implementation but using the Python SDK instead. Creating templates for each supported SDK can help us appear listed on https://www.pulumi.com/templates/kubernetes/.

I've updated the structure with two parent folders, one for python code and another one for nodejs code, and keeping cloud-init under root, so both can take advantage of the same install scripts. However, to appear listed on the templates site, it seems they must be in https://github.com/pulumi/templates and separated into self-contained folders, so we may have to archive this repository, if that is our goal.

NOTE: some parameters, like operating system or metal plan, are not parameterized yet. Instead of that, my idea is to first validate which software versions, OS, plans are compatible, and then create the variables with constraints of allowed values

### CODE REVIEW

**Comment by ctreatma** [comment]
I think pulumi/templates is the best place for this, but we can keep it here for now while we develop it.  Maybe we hold off on advertising it until it's moved, unless moving it over there would take a while.

**Comment by ctreatma** [comment]
It looks like the cloud-init has to be duplicated in each template (potentially a symlink would be enough, but I don't know if that's the case, and we'll have to duplicate anyway if this lands in the official templates repo).  Here are the commands I ran (maybe I did something wrong?):

```bash
$ pulumi new https://github.com/equinix-labs/pulumi-equinix-kubernetes-cluster/tree/python/nodejs
# NOTE: this failed at the end because it couldn't find the `node_modules` dir, even though the directory exists; maybe just a problem on my machine
$ pulumi up
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/ctreatma/metal-k8s-cluster/dev/previews/8c6dafff-3d2f-46d1-9f85-52d93f2a5b5b

     Type                 Name                   Plan       Info
 +   pulumi:pulumi:Stack  metal-k8s-cluster-dev  create     1 error


Diagnostics:
  pulumi:pulumi:Stack (metal-k8s-cluster-dev):
    error: Running program '/Users/ctreatman/Documents/code/pulumi-node-test/src/index.ts' failed with an unhandled exception:
    Error: ENOENT: no such file or directory, open '../cloud-init/scripts/pre-install.sh'
        at Object.openSync (node:fs:590:3)
        at Object.readFileSync (node:fs:458:35)
        at Object.<anonymous> (/Users/ctreatman/Documents/code/pulumi-node-test/src/kubernetes/worker-pool.ts:77:19)
        at Module._compile (node:internal/modules/cjs/loader:1267:14)
        at Module.m._compile (/Users/ctreatman/Documents/code/pulumi-node-test/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/ctreatman/Documents/code/pulumi-node-test/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:1125:32)
        at Function.Module._load (node:internal/modules/cjs/loader:965:12)
        at Module.require (node:internal/modules/cjs/loader:1149:19) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: '../cloud-init/scripts/pre-install.sh'

**Comment by ocobles** [comment]
I didn't realize that install option, and the readme steps I added were to clone the entire repository. I'll see if there is an alternative to not duplicate the scripts

**Comment by ocobles** [comment]
The cloud-init path issue should be fixed now. I have created a branch for cloud-init and used subtree to clone it into the nodejs and python folders. It works well but the system is a bit cumbersome. I'll add a DEVELOPMENT file to define the steps to update the cloud-init scripts

**Comment by ctreatma** [comment]
Didn't run all the way through but I went far enough with each template to confirm that the `ENOENT` is fixed.  Nice work!

**Comment by ocobles** [comment]
I added some notes for the development, as it requires some extra manual steps, although that can be added later in a GH Action, I think that approach could work until moving this content to pulumi/templates. If there are no more objections, this should be ready to merge.

**Review by ctreatma — APPROVED** [review]

**Pull request merged**
